version: "3.9"
services:
  # movie_api:
  #   build: .
  #   container_name: movie_api
  #   environment:
  #     - MOVIE_API_SERVER_PORT_INTERNAL=${MOVIE_API_SERVER_PORT_INTERNAL:-18000}
  #     - MOVIE_API_SERVER_PORT_EXTERNAL=${MOVIE_API_SERVER_PORT_EXTERNAL:-19000}
  #     - POSTGRES_HOST=${POSTGRES_HOST:-localhost}"
  #     - POSTGRES_USER=${POSTGRES_USER:-user}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
  #     - POSTGRES_PORT=${POSTGRES_PORT:-5432}"
  #     - POSTGRES_DATABASE_NAME=${POSTGRES_DATABASE_NAME:-movie}
  #     - JWT_SECRET=${JWT_SECRET:-secret}

        - AUTH_SERVICE_HOST=${AUTH_SERVICE_HOST:-localhost}
        - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT:-17000}
  #   ports:
  #     - "19000:18000"
  postgres:
    image: "postgres:12"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "33000:${POSTGRES_PORT:-5432}"
