version: "3.9"
services:
  movie_api:
    build: .
    container_name: movie_api
    environment:
      - MOVIE_API_SERVER_PORT_INTERNAL=${MOVIE_API_SERVER_PORT_INTERNAL}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE_NAME=${POSTGRES_DATABASE_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - OMDBAPI_KEY=${OMDBAPI_KEY}
    ports:
      - "19000:18000"
    networks:
      - app_net

  postgres:
    image: "postgres:12"
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5432"
    ports:
      - "33000:5432"
    networks:
      - app_net


networks:
  app_net:
    driver: bridge