name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: config ...
    - run: |
        ls
        pwd
        tree -L 2

    - name: Create ENV files
      working-directory: ./movies
      run: |
        ls
        pwd
        node tests/createEnvFiles.js

    - name: Build movies API
      working-directory: movies
      run: |
        ls
        pwd
        yarn
        yarn build
        yarn lint

    - name: Create Auth container
      working-directory: ./auth
      run: |
        ls
        pwd
        docker-compose up -d

    - name: Create Movie API containers
      working-directory: movies
      run: |
        ls
        pwd
        docker-compose up -d

    - name: Run tests
      working-directory: movies
      run: |
        ls
        pwd
        node tests/index.js